name: Build custom Strimzi Kafka Image

'on':
  workflow_dispatch:
    inputs:
      strimzi_version:
        description: 'Strimzi version'
        required: true
        default: 'default'
        type: string
      kafka_version:
        description: 'Kafka version'
        required: true
        default: 'default'
        type: string
  push:
    branches:
    - main
    paths:
    - src/kafka/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build Strimzi Kafka image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:        
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set variables
      run: |
        if [ "${{ inputs.strimzi_version }}" == "" ] || [ "${{ inputs.strimzi_version }}" == "default" ]; then
          STRIMZI_VERSION=$(sed -n 's/^ARG STRIMZI_VERSION=//p' src/kafka/Dockerfile)
        else
          STRIMZI_VERSION=${{ inputs.strimzi_version }}
        fi

        if [ "${{ inputs.kafka_version }}" == "" ] || [ "${{ inputs.kafka_version }}" == "default" ]; then
          KAFKA_VERSION=$(sed -n 's/^ARG KAFKA_VERSION=//p' src/kafka/Dockerfile)
        else
          KAFKA_VERSION=${{ inputs.kafka_version }}
        fi

        echo "STRIMZI_VERSION=$STRIMZI_VERSION" >> $GITHUB_ENV
        echo "KAFKA_VERSION=$KAFKA_VERSION" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Github Packages container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/strimzi/kafka
        tags: |
          type=raw,value=${{ env.STRIMZI_VERSION }}-kafka-${{ env.KAFKA_VERSION }}-{{date 'YYYYMMDD-HHmm'}}
          type=raw,value=${{ env.STRIMZI_VERSION }}-kafka-${{ env.KAFKA_VERSION }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: src/kafka
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          STRIMZI_VERSION=${{ env.STRIMZI_VERSION }}
          KAFKA_VERSION=${{ env.KAFKA_VERSION }}
