name: Mirror karpenter helm chart

'on':
  workflow_dispatch:
    inputs:
      karpenter_version:
        description: 'Karpenter chart version to mirror'
        required: true
        default: '1.4.0'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  mirror-chart:
    name: Mirror helm chart

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Log in to the Github Packages container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull and push helm chart
      run: |
        helm pull --version="${{ inputs.karpenter_version }}" oci://public.ecr.aws/karpenter/karpenter
        helm pull --version="${{ inputs.karpenter_version }}" oci://public.ecr.aws/karpenter/karpenter-crd

        DESTINATION=$(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')
        helm push karpenter-${{ inputs.karpenter_version }}.tgz oci://${DESTINATION}
        helm push karpenter-crd-${{ inputs.karpenter_version }}.tgz oci://${DESTINATION}
